version: "3"

services:
  users-mysql:
    container_name: users-mysql
    image: users-mysql
    ports:
      - "8089:8086"
    networks:
      - employee-mysql-docker
    depends_on:
      - mysql-standalone

  mysql-standalone:
    container_name: mysql-standalone
    image: mysql:5.7.28
    networks:
      - employee-mysql-docker
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password

networks:
  employee-mysql-docker: